### ISSUE TITLE
Add {GLAD}: {Gladius Finance}

### ISSUE THREAD

**Issue by gladiusfynance** [tomochain/luaswap-token-list#1]
- [x] I understand that token listing is not required to use the LuaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the LuaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xd17c60c01a2eb6117fd2afaa942dc465ce9939d1 
Token Name (from contract): 0xf35f3d0823363c343d8e46bd6cc5f78da014c929 
Token Decimals (from contract): 18
Token Symbol (from contract): GLAD
LuaSwap Pair Address of Token: 81806836 
Link to the official homepage of token:https://gladius.finance/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/es/currencies/gladius-finance/social/

**Comment by phucngh** [comment]
LuaSwap Pair Address of Token is incorrect.
