### ISSUE TITLE
Add CBC: Colombo Coin

### ISSUE THREAD

**Issue by vagucs** [tomochain/luaswap-token-list#4]
- [x] I understand that token listing is not required to use the LuaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the LuaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x6ca97401da035e42f4803709e94118260415b6ad
Token Name (from contract): Colombo Coin
Token Decimals (from contract): 18
Token Symbol (from contract): CBC
LuaSwap Pair Address of Token: https://info.luaswap.org/tomochain/token/0x6ca97401da035e42f4803709e94118260415b6ad

Link to the official homepage of token: https://www.crmcoins.com.br/colombocoin
Link to CoinMarketCap or CoinGecko page of token:

**Comment by vagucs** [comment]
Can anyone help?

**Comment by phucngh** [comment]
Your liquidity is too low that we can't accept your request.

**Comment by vagucs** [comment]
What is the required amount?

**Comment by vagucs** [comment]
We are trying to bring the project to our company to present it to an investor, who should provide all the money to provide liquidity, but without presenting the finished roadmap it is difficult, for now I will do what I can. One question, why can't I remove a CBC/WTOMO pair? confirm does not work.

**Comment by phucngh** [comment]
Can't remove a pair after created. We don't support to do it.
You can add more liquidity or remove liquidity on this pair.

**Comment by vagucs** [comment]
Ok, thanks!
